spring:
  datasource:
    url: jdbc:mysql://localhost:3306/barberdb?allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin

clients:
    CLIENT_SERVER: "http://127.0.0.1:5173"