spring:
  datasource:
    url: ${DB_CONNECTION_PROD}
    username: ${DB_USER_PROD}
    password: ${DB_PASSWORD_PROD}

clients:
  CLIENT_SERVER: https://xatruch-barbershop-client.vercel.app
  CLIENT_SERVER_FORGOT_PASSWORD_URI: ""


