spring:
  datasource:
    url: ${DB_CONNECTION}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

clients:
    CLIENT_SERVER: http://127.0.0.1:5173
    CLIENT_SERVER_FORGOT_PASSWORD_URI: http://127.0.0.1:5173/auth/forgot-password/recovery